feat: add markdownlint-rule-github-admonition to rules docker image
DavidAnson/markdownlint-cli2 pull request #133
Opened 2023-03-13 09:47 UTC by aepfli

[GitHub Admonition markdownlint rule](https://github.com/aepfli/markdownlint-rule-github-admonition) was released a few days ago. It allows us to detect and fix GitHub-style admonitions.

With this pull request we also include it into the rules docker image.

2023-03-13 09:48 UTC, aepfli commented
i am sorry, to not generate an issue, but i thought i is not worth it, as the change itself is a Yay-or-Nay kind of change, either it will be used or not :)

2023-03-13 16:08 UTC, DavidAnson commented
No worries, the intent is to include all such rules.

2023-03-13 16:10 UTC, DavidAnson requested changes
Just a trivial request for you...

2023-03-13 16:10 UTC, DavidAnson commented on docker/Dockerfile-rules
> +    markdownlint-rule-github-admonition \
Nitpick: please move up one line to sort alphabetically.

2023-03-13 16:13 UTC, DavidAnson commented
We should wait and then retry the failing link test. It looks like maybe npm is returning HTTP 503 all over the place right now. Unrelated to your change.

2023-03-13 20:01 UTC, aepfli commented
Side question, for the fun of it, I created a dockerfile, which will automatically install all dependencies based on the npmjs API. It is a security risk to trust those sources blindly, but as usual, I thought I share my approach. If you like it, i can open a PR :) - it is a multi-stage build :)

```dockerfile
ARG VERSION
FROM alpine:latest as builder

RUN apk update \
 && apk add --no-cache curl jq \
 && rm -rf /var/cache/apk/*
RUN curl -X GET -H "Content-Type: application/json" \
    "https://registry.npmjs.com/-/v1/search?text=keywords%3Amarkdownlint-rule&size=100" |\
    jq --raw-output '.objects | .[].package.name ' > packages.txt

FROM davidanson/markdownlint-cli2:${VERSION}
USER root
COPY --from=builder packages.txt packages.txt
RUN while read p; do npm install --global --no-package-lock --production $p; done <packages.txt
USER node
```

2023-03-13 20:09 UTC, DavidAnson commented
I like where your head is at, but I would rather manage this directly. :)

2023-03-15 04:10 UTC, DavidAnson approved these changes

2023-03-15 04:11 UTC, merged