add fix command to pre-commit-hooks
DavidAnson/markdownlint-cli2 pull request #37
Opened 2022-02-14 16:56 UTC by Cielquan

closes #36

Discussion was in #36. New PR because of changing target branch.

2022-02-15 02:19 UTC, DavidAnson requested changes
Thanks for adding that! I left two nitpick comments.

2022-02-15 02:19 UTC, DavidAnson commented on .pre-commit-hooks.yaml
> +  description: "Checks the style of Markdown/CommonMark files with a non root config."
How about: "... with a non-root configuration file."

2022-02-15 02:19 UTC, DavidAnson commented on .pre-commit-hooks.yaml
> +  description: "Fix the style of Markdown/CommonMark files."
How about: "Checks and fixes"

2022-02-15 07:19 UTC, Cielquan commented on .pre-commit-hooks.yaml
> +  description: "Checks the style of Markdown/CommonMark files with a non root config."
Sounds good. Will do.

2022-02-15 07:19 UTC, Cielquan commented on .pre-commit-hooks.yaml
> +  description: "Fix the style of Markdown/CommonMark files."
Sounds good. Will do.

2022-02-16 02:59 UTC, DavidAnson approved these changes

2022-02-16 03:04 UTC, merged

2022-02-16 03:06 UTC, DavidAnson commented
Thanks!